### ISSUE TITLE
GA 세팅하기

### ISSUE THREAD

**Issue by mininim** [DeveloperAcademy-POSTECH/MacC-Team-1010#116]
## 🛠 Issue
Google GA 세팅하기

## 📝 To-do

- [ ] Google GA 의존성 추가 
- [ ] API Key 추가 
- [ ] GA Manager 구현

**Comment by mininim** [comment]
Amplitude사용하기로
