### ISSUE TITLE
홈(메인뷰) UI 변경사항 적용

### ISSUE THREAD

**Issue by ungchun** [DeveloperAcademy-POSTECH/MacC-Team-1010#124]
## 🛠 Issue
2차 업데이트에 맞게 수정된 홈 UI 변경사항을 적용합니다.

## 📝 To-do

- [x] 코멘트가 달렸어요
- [x] 카테고리 뷰 sort 로직 구현
- [x] 새로 나왔어요 뷰 변경
- [ ] 주제로 찾기 추가
