### ISSUE TITLE
2차 찐막 QA

### ISSUE THREAD

**Issue by mininim** [DeveloperAcademy-POSTECH/MacC-Team-1010#138]
## 🛠 Issue
ver1.1.0 2차 QA 수정

## 📝 To-do

- [x] request mark Alert 추가
- [x] 회원가입 완료 alert 삭제
- [x] version text 수정
