### ISSUE TITLE
Tuist 모듈 수정 및 네트워크 구조 세팅

### ISSUE THREAD

**Issue by ungchun** [DeveloperAcademy-POSTECH/MacC-Team-1010#22]
## 🛠 Issue
하이파이에 맞춰 모듈 수정하고 네트워크 기본 구조를 세팅합니다.

## 📝 To-do

- [x] Tuist 구조 수정
- [x] 폴더, 파일 네이밍 수정
- [x] 디자인 컬러 컴포넌트 set 추가
