### ISSUE TITLE
네트워크 에러 로직 및 api 추가

### ISSUE THREAD

**Issue by ungchun** [DeveloperAcademy-POSTECH/MacC-Team-1010#51]
## 🛠 Issue

네트워크 에러 로직 추가 및 추가된 api 로직 설계

## 📝 To-do

- [x] 추가된 네트워크 로직 추가
- [x] Logger extension 추가
- [x] 네트워크 에러 로직 추가
- [x] !, ?? 로직 제거 및 수정
