### ISSUE TITLE
API 통신 로직 추가 및 네트워크 코드 리팩토링

### ISSUE THREAD

**Issue by ungchun** [DeveloperAcademy-POSTECH/MacC-Team-1010#56]
## 🛠 Issue

API 통신 로직 추가 및 네트워크 코드 리팩토링

## 📝 To-do

- [x] API 추가
- [x] response, request public 수정
- [x] 구조체 네이밍 수정
- [x] 내비게이션 title inline으로 수정
