### ISSUE TITLE
막걸리 평가 API 연결

### ISSUE THREAD

**Issue by mininim** [DeveloperAcademy-POSTECH/MacC-Team-1010#65]
## 🛠 Issue
InformationView에서 막걸리 평가 (좋았어요, 아쉬워요) API 연결

## 📝 To-do

- [x] EvaluateMakRequest 타입 구현
- [x] EvaluateMakResponse 타입 구현
- [x] UserRepository - evaluateMak  구현
- [x] InformationViewModel - 평가 로직 구현
