### ISSUE TITLE
InformationView 디자인 QA 수정

### ISSUE THREAD

**Issue by mininim** [DeveloperAcademy-POSTECH/MacC-Team-1010#88]
## 🛠 Issue
InformationView 디자인 QA 내용 수정합니다. 

## 📝 To-do

- [x] 백그라운드 컬러
- [x]  CardView 백그라운드 변경 
- [x] MakHolyImageview 크기 확인
- [x] TasteScroeView 패딩 값 확인
- [x] 평가 및 코멘트 Text 정렬 
- [x] 코멘트 작성 화면 UI 
- [x] 코멘트 작성, 작성 버튼 활성화 로직
- [x] 디바이더 확인 
- [x] 패딩 확인 

## 추가 
- [x] 코멘트 상세 화면 넘어가는 기준 코멘트 2개
- [x] Text Spacing 업데이트
- [x] Date Converting
- [x] 상단 statusbar 없애기 
- [x] 코멘트 없는 경우 InfoCommentList 텍스트 내용 수정
- [x]  좋아요수 보여주는 기준  → 5개 / 평가 수 텍스트 추가
- [x]  코멘트 작성 - 뒤에 공백만 삭제 / 줄 제한 없음
- [x]  Comment Edit Sheet 에서 키보드 올라와있기 기본 상태로
- [x]  InformationView 모달 형식으로
- [x] 상단 toolbar 변경
- [x] Info AwardsView 정렬 변경
- [x]  지난 코드 리뷰들 한번 확인하기
- [x] 최초 fetchData progress
- [x] 코멘트 Detail List View 확인 
- [x] InformationView 상단 바 크기 확인 
- [x] 와따많구만
